# Generated by Django 5.1.1 on 2024-11-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermessage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
