# Generated by Django 5.1.3 on 2024-11-29 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tool_description_alter_tool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
