# Generated by Django 5.1.1 on 2024-11-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_usermessage_deleted_at_usermessage_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantmessage",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistantmessage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
