# Generated by Django 5.1.1 on 2024-09-16 00:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_conversation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("07b4cf38-e45c-4464-adac-16039fa47c68"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
