# Generated by Django 5.1.3 on 2024-11-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tool_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
