# Generated by Django 5.1.1 on 2024-09-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantmessage",
            name="liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="liked",
            field=models.BooleanField(default=False),
        ),
    ]
