# Generated by Django 5.1.3 on 2024-11-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tool_created_at_tool_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='script',
            field=models.TextField(blank=True, default=''),
        ),
    ]
