# Generated by Django 5.1.1 on 2024-09-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_ollamamodel_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="user_messages/"),
        ),
    ]
