# Generated by Django 5.1.3 on 2024-12-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_tool_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
