# Generated by Django 5.1.1 on 2024-09-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_usermessage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ollamamodel",
            name="color",
            field=models.CharField(default="gray", max_length=25),
        ),
        migrations.AlterField(
            model_name="usermessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_message_images/"
            ),
        ),
    ]
