# Generated by Django 5.1.3 on 2024-12-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantmessage",
            name="tools_used",
            field=models.JSONField(default=None, null=True),
        ),
    ]
