# Generated by Django 5.1.1 on 2024-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_ollamamodel_color_alter_usermessage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ollamamodel",
            name="color",
            field=models.CharField(
                choices=[
                    ("Gray", "gray"),
                    ("Mauve", "mauve"),
                    ("Slate", "slate"),
                    ("Sage", "sage"),
                    ("Olive", "olive"),
                    ("Sand", "sand"),
                    ("Tomato", "tomato"),
                    ("Red", "red"),
                    ("Ruby", "ruby"),
                    ("Crimson", "crimson"),
                    ("Pink", "pink"),
                    ("Plum", "plum"),
                    ("Purple", "purple"),
                    ("Violet", "violet"),
                    ("Iris", "iris"),
                    ("Indigo", "indigo"),
                    ("Blue", "blue"),
                    ("Cyan", "cyan"),
                    ("Teal", "teal"),
                    ("Jade", "jade"),
                    ("Green", "green"),
                    ("Grass", "grass"),
                    ("Bronze", "bronze"),
                    ("Gold", "gold"),
                    ("Brown", "brown"),
                    ("Orange", "orange"),
                    ("Amber", "amber"),
                    ("Yellow", "yellow"),
                    ("Lime", "lime"),
                    ("Mint", "mint"),
                    ("Sky", "sky"),
                ],
                default="Gray",
                max_length=25,
            ),
        ),
    ]
