# Generated by Django 5.1.3 on 2025-02-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_assistantmessage_tools_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistantmessage",
            name="model",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.model"
            ),
        ),
    ]
