# Generated by Django 5.1.6 on 2025-02-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_assistantmessage_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="use_tools",
            field=models.BooleanField(default=False),
        ),
    ]
