# Generated by Django 5.1.1 on 2024-09-29 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_ollamamodel_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistantmessage",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.ollamamodel"
            ),
        ),
    ]
