# Generated by Django 5.1.1 on 2024-10-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_assistantmessage_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermessage",
            name="image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="user_message_images/"
            ),
        ),
    ]
