# Generated by Django 5.1.1 on 2024-10-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_model_delete_provider_alter_assistantmessage_model"),
        ("users", "0008_alter_profile_preferred_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OllamaModel",
        ),
    ]
