.PHONY: tail
tail:
	npx tailwindcss -i ./src/styles/index.css -o ./src/styles/output.css 

.PHONY: tailw
tailw:
	npx tailwindcss -i ./src/styles/index.css -o ./src/styles/output.css --watch

.PHONY: run
run:
	npm run dev