version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - DJANGO_SUPERUSER_USERNAME=ethan
        - DJANGO_SUPERUSER_PASSWORD=ethan
        - DJANGO_SUPERUSER_EMAIL=ethanlchristensen@outlook.com
        - OLLAMA_HOST=http://host.docker.internal:11434
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=ethan
      - DJANGO_SUPERUSER_PASSWORD=ethan
      - DJANGO_SUPERUSER_EMAIL=ethanlchristensen@outlook.com
      - OLLAMA_HOST=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - VITE_APP_BACKEND_API_URL=http://localhost:8000/api/v1/
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend