# Generated by Django 5.1.3 on 2024-11-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='use_tools',
            field=models.BooleanField(default=False),
        ),
    ]
