# Generated by Django 5.1.1 on 2024-11-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_settings_theme"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="settings",
            options={"verbose_name": "Setting", "verbose_name_plural": "Settings"},
        ),
    ]
