# Generated by Django 5.1.1 on 2024-09-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_user_customuser_alter_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="perfered_model",
            new_name="perferred_model",
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default/default.png", upload_to="profile_pics"
            ),
        ),
    ]
