# Generated by Django 5.1.1 on 2024-11-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_settings_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="recovery_hours",
            field=models.IntegerField(default=24),
        ),
    ]
