# Generated by Django 5.1.1 on 2024-11-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_settings_recovery_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="recovery_hours",
        ),
    ]
