# Generated by Django 5.1.1 on 2024-09-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_perferred_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="perferred_model",
            new_name="preferred_model",
        ),
    ]
