# Generated by Django 5.1.1 on 2024-09-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_perferred_model_profile_preferred_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default/default.jpg", upload_to="profile_pics/"
            ),
        ),
    ]
