# Generated by Django 5.1.1 on 2024-10-17 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_model_delete_provider_alter_assistantmessage_model"),
        ("users", "0007_alter_profile_bio_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="preferred_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_model",
                to="api.model",
            ),
        ),
    ]
